sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION root/scalastyle testSuiteJVM/scalastyle testSuiteJVM/test:scalastyle testSuiteJS/scalastyle testSuiteJS/test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION testSuiteJVM/test
  - sbt ++$TRAVIS_SCALA_VERSION testSuiteJS/test
  - sbt ++$TRAVIS_SCALA_VERSION 'set scalaJSStage in Global := FullOptStage' testSuiteJS/test
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal
scala:
  - 2.10.6
  - 2.11.11
  - 2.12.2
  - 2.13.0-M1
jdk:
  - oraclejdk8
env:
  - SCALAJS_VERSION=0.6.18
  - SCALAJS_VERSION=1.0.0-M1

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
